webtalk_init -webtalk_dir /home/root07/Desktop/Final year/VAC Work/HC08 datapath/status_bit_reg/status_bit_reg.sim/sim_1/behav/xsim/xsim.dir/reg_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Feb  2 17:42:57 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "49e6ffc9-04a7-4ffb-82d9-c09f4fe1b240" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cf9e256ee4ba49f9a8107e929a603943" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2087.250 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125692_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1464048913 -regid "" -xml /home/root07/Desktop/Final year/VAC Work/HC08 datapath/status_bit_reg/status_bit_reg.sim/sim_1/behav/xsim/xsim.dir/reg_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/root07/Desktop/Final year/VAC Work/HC08 datapath/status_bit_reg/status_bit_reg.sim/sim_1/behav/xsim/xsim.dir/reg_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/root07/Desktop/Final year/VAC Work/HC08 datapath/status_bit_reg/status_bit_reg.sim/sim_1/behav/xsim/xsim.dir/reg_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
